Make pyaudio_oscope_local.py example repeatable
# pyaudio_oscope_local.py - main: stop and close pyaudio node to properly close pyaudio
# Otherwise, an error appears in succesive executions: 
# ValueError: Input not supported: channels=1 samplerate=44100.0 device_id=2

# audio_pyaudio.py - PyAudio._close
# Condition added to address the fact that thread is only created when self.output_device_index is not None
# otherwise: AttributeError: thread

# stream.py - InputStream.close
# There are situations in which input does not need to be connected (namely audio_pyaudio node) and hence, trying to access for closing produces an error
#  AttributeError: 'InputStream' object has no attribute 'receiver'
#  Try...catch added around- self.receiver.close()
# same for socket
# Evaluate if the same applies to OutputStream.close